### ISSUE TITLE
DataTable - In the latest version, the NEXT button goes outside the block

### ISSUE THREAD

**Issue by m3nur** [Devwares-Team/cdbreact#17]
![Vite + React](https://user-images.githubusercontent.com/45517204/220888496-bddb56dc-d59c-4a59-b680-34f327517ad6.png)

**Comment by NurMura88** [comment]
![Vite + React](https://user-images.githubusercontent.com/45517204/220888428-bc70c97e-34d2-46ed-a06c-6061370623d6.png)

**Comment by Speedwares** [comment]
Hey @NurMura88 Unfortunately I was not able to replicate this. Can you try replicating this somewhere like https://codesandbox.io/. I am guessing this is due to styles you added to your own project.

Can you also confirm if you are following this example on our documentation page https://www.devwares.com/docs/contrast/react/table/datatables/ ?

**Comment by m3nur** [comment]
https://codesandbox.io/s/epic-gould-z48ho6?file=/src/App.js 
![epic-gould-z48ho6 - CodeSandbox](https://user-images.githubusercontent.com/45517204/221181030-6d267e77-9c5b-48fe-9035-1ebfdc95c66c.png) 
I don't know exactly what the width of the screen is here.

**Comment by Speedwares** [comment]
@m3nur this has been fixed in the latest version! Thanks for reporting. 
Can you confirm on your end?

**Comment by m3nur** [comment]
Everything is fixed!!!
