### ISSUE TITLE
Stepper component trailing line on last step

### ISSUE THREAD

**Issue by buildxyz-git** [Devwares-Team/cdbreact#29]
I have a simple issue, when I create the following horizontal stepper:
```javascript
<CDBStepper
    stepSize={35}
    showTitle={true}
    showTooltip={true}
>
    <CDBStep
        id={0}
        icon="ruler-combined"
        name="Zero"
        handleClick={() => handleNextPrevClick(0)}
        active={active}
    />
    <CDBStep
        id={1}
        icon="info-circle"
        name="One"
        handleClick={() => handleNextPrevClick(1)}
        active={active}
    />
    <CDBStep
        id={2}
        icon="square"
        name="Two"
        handleClick={() => handleNextPrevClick(2)}
        active={active}
    />
    <CDBStep
        id={3}
        icon="check"
        name="Three"
        handleClick={() => handleNextPrevClick(3)}
        active={active}
    />
</CDBStepper>
```

I get this with a tailing line at the end. How does `CDBStepper` know when to omit the tailing line on the last `CDBStep` element?
![Screenshot 2023-04-18 at 8 26 54 AM](https://user-images.githubusercontent.com/16586332/232827424-bc2dd43c-3d0c-446c-8668-743db50de471.png)

**Comment by Speedwares** [comment]
Currently `CDBStepper` uses the number in the last id of `CDBStep` to know when to omit a trailing line. So if you changed your steps from to 1,2,3,4 it should omit the last trailing line.

But thinking more about it now, we can refactor this to use the no of children inside the CDBStepper instead, since this can easily be missed. I will leave this issue open as a reference for when the refactoring is done.  

Thanks for reporting this!
