### ISSUE TITLE
Create a .npmignore

### ISSUE THREAD

**Issue by L1lith** [Devwares-Team/cdbreact#5]
You appear to be missing a `.npmignore` which can significantly reduce your bundle sizes on NPM. Things like examples, documentation, IDE and styling config files are all unnecessary to be put on NPM.

**Comment by Speedwares** [comment]
Yeah you are right, the real reason is because I am compiling the library and pushing to npm in another repo and not this one. But I am currently going to bring everything over to this repo to help stay consistent with changes and not having to do it twice. I chose this setup of two repos primarily because the actual repo I use to compile was not in the best arrangement when I released this. But merging soon
